name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - name: Build
        run: npm run docs:build

      - name: List files in dist directory
        run: ls -R docs/.vitepress/dist

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      - name: List files in pages artifact
        run: ls -R ${{ steps.upload-pages-artifact.outputs.path }}

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
